### ISSUE TITLE
We start pNFT migrate from metaplex site with ledger. And can't now start or update authority with goose

### ISSUE THREAD

**Issue by kaerur** [metaplex-foundation/goose#11]
We start pNFT migrate from metaplex site with ledger.
And can't start process.
So change all update authority of nfts to new wallet.
But now can't update authority that regisetered to collection_info.
![image](https://user-images.githubusercontent.com/114330558/219873167-9ecc642e-547e-463b-9cc4-e92e89f3a09d.png)
Can 't use keypair because it is ledger wallet.
Please make goose cli can use with wallet sign or remove our account from program.
https://solscan.io/account/32UBY2qFfWFxxpv6SWctgRr95LnLC9EFGo2yUFVuLXqR

**Comment by samuelvanderwaal** [comment]
Goose doesn't currently have support for Ledger wallets, I'm not sure if we'll be able to add that. If you want an immediate solution you can migrate your items to a new Collection using [collections.metaplex.com](https://collections.metaplex.com/) or [metaboss](https://github.com/samuelvanderwaal/metaboss).

**Comment by kaerur** [comment]
I finally changed authority from Ledger wallet to normal wallet.
But still get error while migrate it, like this.
![image](https://user-images.githubusercontent.com/114330558/220547596-7b65a9be-3788-45bc-801e-a60e01d89e75.png)
This is error
![image](https://user-images.githubusercontent.com/114330558/220547766-891516a8-97e2-4ba4-96d2-16f2d7e26fbe.png)
Please review it and reply me that's wrong with it.

Info Bellow.

mint: 5iwFavPxXKvnSoyPWHzYB6F5EfbvQq6U3jrS7GXUs3EA
authority: AxVR1S5Wzp74YfzDYespasU5cgjjemR33uMsaQF2Tp7H
rule_set: eBJLFYPxJmMGKuFwpDWkzxZeUrad92kZRC5BJLpzyT9
delegate_record: BP2gHVFZG7HbYWJNgL4PYGQLASoQLzyDeRjLooBz8cRh
status: MigrationStatus {
        unlock_time: 1674595820,
        is_locked: false,
        in_progress: true,
        items_migrated: 0,
 },

**Comment by samuelvanderwaal** [comment]
@happyday03518 have you updated *all* of the NFTs in the collection to the new update authority or just the collection parent NFT?

**Comment by kaerur** [comment]
I updated all nfts of course. But If I start migration via metaboss. No one success, Same from royaty,metaplex.com.

**Comment by samuelvanderwaal** [comment]
> I updated all nfts of course. But If I start migration via metaboss. No one success, Same from royaty,metaplex.com.

Ok, as long as all NFT items have the same update authority as the collection we can fix this. I am working on a solution, please give me a couple of hours. :slightly_smiling_face:

**Comment by samuelvanderwaal** [comment]
@happyday03518 In the mean time can you give me a couple example NFT mints from the collection?

**Comment by kaerur** [comment]
Yes. ["Fdpt8VF5qsDSZjJgb3RQUXH3yK6CqSvrfrmoygxC6iv6" , "DbKMU1tmGD46YJs4qCQ5wMqfEuojWMHhNzUE8xFS9Jco"]
These two are nfts of collection.  Let me know if you need whole list. Thank you.

**Comment by samuelvanderwaal** [comment]
Fixing this is more complicated than I anticipated but I think I can figure out a solution tomorrow.

**Comment by kaerur** [comment]
Thank you very much.

**Comment by samuelvanderwaal** [comment]
@happyday03518 you should be able to run `goose start` again to update the delegate record and after that you should be able to migrate. If you have issues with some of the migration failing please see the new `goose check` command which will let you get a list of ones that are unmigrated so you only have to re-run failed attempts.

**Comment by kaerur** [comment]
Yeah. Thanks to your work , problem solved successfuly.
Thank you very much cool man.
